#!/usr/bin/env ruby
# frozen_string_literal: true
$LOAD_PATH.unshift(File.expand_path('../../lib', __FILE__))

require 'gambiarra/ui'

module Gambiarra
  module UI
    class App < Gambiarra::App

    end
  end
end

Gambiarra::UI::App.start(ARGV.join(' '))
